### ISSUE TITLE
Provide Atom/RSS feed

### ISSUE THREAD

**Issue by cipriancraciun** [mattmole/LNL-Discoveries#2]
First of all: great work!

I would also be nice to have an RSS / Atom feed for these links.

**Comment by mattmole** [comment]
Hi,

Thanks for the message and the suggestion. By this, do you mean that there could be a link back to the LateNightLinux site to the episode in questions?

e.g. when reveng was discussed in episode 217, I should provide a link back to https://latenightlinux.com/late-night-linux-episode-217/

EDIT: Ignore me, I already do that. Can you give me an example please?

Thanks

**Comment by cipriancraciun** [comment]
Taking the following file: <https://github.com/mattmole/LNL-Discoveries/blob/main/LateNightLinuxMkDocs/docs/2023/Late%20Night%20Linux%20%E2%80%93%20Episode%20213.md>, each of the links would become a separate RSS item with the link label as the RSS item title, and the link URL as the RSS item URL.

Taking all the files, with all their links, would then create an RSS feed that one could easily consume.

The exact article where the link was presented doesn't mater.  (Just like `lobste.rs` links feed.)

**Comment by mattmole** [comment]
Thank you. I'll do some research to see how easily I could accomplish this with MKDocs, or whether I'd need to do something else

**Comment by mattmole** [comment]
Hi. Could I ask you to test the RSS feed functionality please when I've got it completed and uploaded? I think I've implemented what you asked for. My only issue is that I can only seem to get the RSS item link to point back to the discoveries site, but in the body of the item I am including a link to the discovery itself

**Comment by cipriancraciun** [comment]
Sure, let me know when I can test something.

I'll give you my feedback, and perhaps suggestions on how to improve it if I can.

(If you point me to the code where it's implemented, which I'm assuming it's based on some templating language, I could provide concrete feedback.)

**Comment by mattmole** [comment]
Perfect - thank you.

I've started to use a different theme for MKDocs and along with that choice I've tweaked the code as follows:

1) Use Jinja2 to create the md files, rather than what I did before (write lines of strings to the files)
2) Generate an md file for each discovery, which I then use to generate the RSS feed
3) Hide these RSS files from the navigation so that only the episode files show

You can see the RSS feed at https://mattmole.co.uk/LNL-Discoveries/feed_rss_created.xml and I've deleted and regenerated the files a few times and the RSS reader in thunderbird doesn't seem to pull in any duplicates - which was a good start!

In the main branch you will see a templates folder and the rss generation template is in there. There's also reference to the RSS plugin in the mkdocs.yml file

rssScrapeMD3.py is the Python file that's been used for this new line of work.

Please excuse the messy nature of how I've done things - I have no confidence in using git, so didn't use the branching functionality very well at all.

I'll add a link to the RSS feed when it looks to be working satisfactorily - I don't use RSS readers these days, so don't know what to test really.

Thanks again

**Comment by mattmole** [comment]
Hi @cipriancraciun, no pressure, or rush, but just wondering if you saw my last message? Matt

**Comment by cipriancraciun** [comment]
@mattmole Sorry, it was a busy weekend.  :)

The RSS feed looks OK and works OK at least in my `newsboat` RSS reader.

With regard to duplicates:  the key here (from what I remember is the `guid` field which shouldn't change).  I would suggest using something like an MD5/SHA1 of the string `225:https://clark.center/about` (episode number, discovery actual URL), which will let you then refactor the URL's if needed (which are currently used as `guid`).  (But this is just a "weak suggestion".)

A somewhat "stronger" suggestion is that instead of linking to the HTML page used to generate the RSS contents from, to use as the `link` item directly the discovery URL, i.e. `<link>ttps://clark.center/about</link>`.  The reason is because the contents of the page already exists in the RSS thus was already seen by the user, thus opening the RSS "link" would just show the same thing a second time.

All in all it's great as it is right now!  I've already added it to my RSS and will follow it.
Thanks!
